server:
  port: 8080


spring:
  application:
    name: dm-monitor
    version: 6.0.0

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.4.38:5431/gang
    username: postgres
    password: postgres

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

dm:
  monitor:
    dir: D:/listenDir

swagger:
  enabled: true
  title: 二次开发文档
  version: ${spring.application.version}
  description: 可用接口,供二次开发使用
  contact:
    name: 李刚
  exclude-path: /error,/actuator/**
  authorization:
    name: 认证头
    key-name: Authorization
